default:
  image: node:22-alpine
  tags:
    - hva

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd Website/study-spot
    - npm install
    - npm run build

unit-test-job:
  stage: test
  script:
    - cd Website/study-spot
    - npm install
    - npm run test

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd Website/study-spot
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
